// IVDS Icons Library
// A comprehensive icon library for the Ivoire Design System

// Types and utilities
export type { IconProps } from './types';
export { defaultIconProps } from './types';
export { createIcon, createFilledIcon } from './createIcon';

// Navigation Icons
export {
  IconArrowLeft,
  IconArrowRight,
  IconArrowUp,
  IconArrowDown,
  IconArrowUpRight,
  IconArrowDownLeft,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconChevronDown,
  IconChevronsLeft,
  IconChevronsRight,
  IconHome,
  IconMenu,
  IconMenuAlt,
  IconMoreHorizontal,
  IconMoreVertical,
  IconExternalLink,
  IconCornerDownRight,
  IconRefresh,
  IconRotateCw,
  IconRotateCcw,
} from './navigation';

// Action Icons
export {
  IconPlus,
  IconMinus,
  IconX,
  IconCheck,
  IconEdit,
  IconEdit2,
  IconTrash,
  IconTrash2,
  IconCopy,
  IconClipboard,
  IconDownload,
  IconUpload,
  IconSave,
  IconShare,
  IconShare2,
  IconPrint,
  IconSearch,
  IconZoomIn,
  IconZoomOut,
  IconFilter,
  IconSliders,
  IconSettings,
  IconLock,
  IconUnlock,
  IconEye,
  IconEyeOff,
  IconSend,
  IconLogIn,
  IconLogOut,
  IconMaximize,
  IconMinimize,
} from './actions';

// Status & Feedback Icons
export {
  IconAlertCircle,
  IconAlertTriangle,
  IconCheckCircle,
  IconCheckCircle2,
  IconXCircle,
  IconInfo,
  IconHelpCircle,
  IconAlertCircleFill,
  IconCheckCircleFill,
  IconXCircleFill,
  IconInfoFill,
  IconLoader,
  IconLoader2,
  IconCircle,
  IconCircleDot,
  IconThumbsUp,
  IconThumbsDown,
  IconStar,
  IconStarFill,
  IconStarHalf,
  IconHeart,
  IconHeartFill,
  IconBell,
  IconBellOff,
  IconBellRing,
} from './status';

// UI & Layout Icons
export {
  IconCalendar,
  IconClock,
  IconMail,
  IconPhone,
  IconMapPin,
  IconGlobe,
  IconUser,
  IconUsers,
  IconUserPlus,
  IconUserMinus,
  IconUserCheck,
  IconFile,
  IconFileText,
  IconFolder,
  IconFolderOpen,
  IconImage,
  IconVideo,
  IconGrid,
  IconList,
  IconColumns,
  IconLayout,
  IconSidebar,
  IconPlay,
  IconPause,
  IconStop,
  IconSkipBack,
  IconSkipForward,
  IconVolume,
  IconVolume1,
  IconVolume2,
  IconVolumeX,
  IconShoppingCart,
  IconShoppingBag,
  IconCreditCard,
  IconTag,
  IconMessageCircle,
  IconMessageSquare,
  IconAtSign,
  IconLink,
  IconLinkExternal,
  IconBookmark,
  IconBookmarkFill,
  IconFlag,
  IconAward,
  IconGift,
  IconZap,
  IconZapFill,
  IconCloud,
  IconSun,
  IconMoon,
  IconPaperclip,
  IconCode,
  IconTerminal,
  IconDatabase,
  IconBox,
  IconPackage,
  IconShieldCheck,
  IconLayers,
} from './ui';

// Social Media Icons
export {
  IconTwitter,
  IconX as IconXSocial,
  IconFacebook,
  IconInstagram,
  IconLinkedin,
  IconGithub,
  IconYoutube,
  IconTiktok,
  IconWhatsapp,
  IconDiscord,
  IconSlack,
  IconDribbble,
  IconFigma,
} from './social';

// Icon categories for documentation
export const iconCategories = {
  navigation: [
    'ArrowLeft', 'ArrowRight', 'ArrowUp', 'ArrowDown', 'ArrowUpRight', 'ArrowDownLeft',
    'ChevronLeft', 'ChevronRight', 'ChevronUp', 'ChevronDown', 'ChevronsLeft', 'ChevronsRight',
    'Home', 'Menu', 'MenuAlt', 'MoreHorizontal', 'MoreVertical', 'ExternalLink',
    'CornerDownRight', 'Refresh', 'RotateCw', 'RotateCcw',
  ],
  actions: [
    'Plus', 'Minus', 'X', 'Check', 'Edit', 'Edit2', 'Trash', 'Trash2',
    'Copy', 'Clipboard', 'Download', 'Upload', 'Save', 'Share', 'Share2', 'Print',
    'Search', 'ZoomIn', 'ZoomOut', 'Filter', 'Sliders', 'Settings',
    'Lock', 'Unlock', 'Eye', 'EyeOff', 'Send', 'LogIn', 'LogOut', 'Maximize', 'Minimize',
  ],
  status: [
    'AlertCircle', 'AlertTriangle', 'CheckCircle', 'CheckCircle2', 'XCircle',
    'Info', 'HelpCircle', 'AlertCircleFill', 'CheckCircleFill', 'XCircleFill', 'InfoFill',
    'Loader', 'Loader2', 'Circle', 'CircleDot',
    'ThumbsUp', 'ThumbsDown', 'Star', 'StarFill', 'StarHalf', 'Heart', 'HeartFill',
    'Bell', 'BellOff', 'BellRing',
  ],
  ui: [
    'Calendar', 'Clock', 'Mail', 'Phone', 'MapPin', 'Globe',
    'User', 'Users', 'UserPlus', 'UserMinus', 'UserCheck',
    'File', 'FileText', 'Folder', 'FolderOpen', 'Image', 'Video',
    'Grid', 'List', 'Columns', 'Layout', 'Sidebar',
    'Play', 'Pause', 'Stop', 'SkipBack', 'SkipForward', 'Volume', 'Volume1', 'Volume2', 'VolumeX',
    'ShoppingCart', 'ShoppingBag', 'CreditCard', 'Tag',
    'MessageCircle', 'MessageSquare', 'AtSign', 'Link', 'LinkExternal',
    'Bookmark', 'BookmarkFill', 'Flag', 'Award', 'Gift', 'Zap', 'ZapFill',
    'Cloud', 'Sun', 'Moon', 'Paperclip', 'Code', 'Terminal', 'Database', 'Box', 'Package',
    'ShieldCheck', 'Layers',
  ],
  social: [
    'Twitter', 'XSocial', 'Facebook', 'Instagram', 'Linkedin', 'Github',
    'Youtube', 'Tiktok', 'Whatsapp', 'Discord', 'Slack', 'Dribbble', 'Figma',
  ],
} as const;

// Total icon count
export const ICON_COUNT = Object.values(iconCategories).flat().length;
