#!/usr/bin/env node

/**
 * Generate icon SCSS files from SVG sources
 * Creates individual SCSS files with inlined SVG data URIs
 */

const fs = require('fs');
const path = require('path');
const { glob } = require('glob');

const SVG_DIR = 'src/svg';
const OUTPUT_DIR = 'src/icons';

/**
 * Convert SVG content to data URI
 */
function svgToDataUri(svgContent) {
  // Clean up SVG
  let cleaned = svgContent
    .replace(/\r?\n|\r/g, ' ') // Remove newlines
    .replace(/\s+/g, ' ') // Collapse whitespace
    .replace(/>\s+</g, '><') // Remove space between tags
    .trim();
  
  // URL encode for data URI
  const encoded = cleaned
    .replace(/"/g, "'")
    .replace(/%/g, '%25')
    .replace(/#/g, '%23')
    .replace(/{/g, '%7B')
    .replace(/}/g, '%7D')
    .replace(/</g, '%3C')
    .replace(/>/g, '%3E')
    .replace(/\s+/g, '%20');
  
  return `url("data:image/svg+xml;charset=utf-8,${encoded}")`;
}

async function generateIconCSS() {
  console.log('🎨 Generating icon SCSS files from SVG sources...\n');
  
  // Ensure output directory exists
  if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  }
  
  const svgFiles = await glob(`${SVG_DIR}/**/*.svg`);
  const icons = [];
  
  for (const svgPath of svgFiles) {
    const iconName = path.basename(svgPath, '.svg');
    const outputPath = path.join(OUTPUT_DIR, `${iconName}.scss`);
    
    // Read and inline SVG
    const svgContent = fs.readFileSync(svgPath, 'utf-8');
    const dataUri = svgToDataUri(svgContent);
    
    // Create SCSS with inlined SVG data URI
    const scss = `.ivds-icon--${iconName} {
  --mask-image-${iconName}: ${dataUri};
  --mask-image: var(--mask-image-${iconName});
}

.ivds-icon-start--${iconName} {
  --mask-image-before: var(--mask-image-${iconName});
}

.ivds-icon-end--${iconName} {
  --mask-image-after: var(--mask-image-${iconName});
}
`;
    
    fs.writeFileSync(outputPath, scss);
    icons.push({ name: iconName, file: `${iconName}.scss` });
  }
  
  console.log(`✓ Generated ${icons.length} icon SCSS files with inlined SVGs\n`);
  
  // Generate icons.scss that imports all icons
  const importsScss = icons
    .map(icon => `@import "${icon.file}";`)
    .join('\n');
  
  const iconsScss = `/**
 * IVDS Icons
 * Auto-generated icon imports
 * DO NOT EDIT MANUALLY - Generated by scripts/generateIcons.js
 */
@import "./_icon.scss";
${importsScss}
`;
  
  fs.writeFileSync(path.join(OUTPUT_DIR, 'icons.scss'), iconsScss);
  console.log(`✓ Generated icons.scss with ${icons.length} icon imports\n`);
  
  // Generate icons-modern.scss (same as icons.scss for now)
  fs.writeFileSync(path.join(OUTPUT_DIR, 'icons-modern.scss'), iconsScss);
  console.log(`✓ Generated icons-modern.scss\n`);
  
  // Generate icon list for documentation
  const iconList = icons.map(i => i.name).sort();
  console.log('📋 Available icons:');
  console.log(`   Total: ${iconList.length} icons`);
  console.log(`   First 10: ${iconList.slice(0, 10).join(', ')}...`);
  
  return icons;
}

generateIconCSS()
  .then(() => {
    console.log('\n✅ Icon generation complete!');
  })
  .catch(error => {
    console.error('\n❌ Error generating icons:', error);
    process.exit(1);
  });
